#!/bin/sh

song() {
	# Song
	song=$(playerctl metadata title -s)

	if [ "$song" == "" ]; then
		song=""
	else
		song=" [ $song] "
	fi
}

vol() {
	# Volume
	volpercent=$(pamixer --get-volume-human)
	if [ "$volpercent" == "muted" ]; then
		volpercent="M"
	fi
	vol=" [墳 $volpercent] "
}

batt() {
	# Battery
	battpercent=$(acpi -b | grep -P -o '[0-9]+(?=%)')
	charging=$(acpi -b | grep -o -F "Charging")
	discharging=$(acpi -b | grep -o -F "Discharging")
	if [ "$charging" == "Charging" ]; then
		battsymbol=""
	elif [ "$discharging" == "Discharging" ]; then
		battsymbol=""
	else
		battsymbol=""
	fi
	batt=" [$battsymbol $battpercent%] "
}

datetime() {
	date=" [ $(date +%a) $(date +%d/%m/%Y)] "
	if [ "$1" == "false" ]; then
		time=" [ $(date +%H) $(date +%M) $(date +%S)] "
	else
		time=" [ $(date +%H:%M:%S)] "
	fi
}

status() {
	echo $1
	song
	vol
	batt
	datetime $1
	text="$song$vol$batt$date$time"
}

colons="true"

while true
do
	status $colons
	xsetroot -name "$text"
	if [ $colons == "true" ]; then
		colons="false"
	else
		colons="true"
	fi
	sleep 1s
done
